controller_manager:
  ros__parameters:
    update_rate: 160

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  
  ros__parameters:

    joints:
      - joint_1
      - joint_2
      - joint_3
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    allow_nonzero_velocity_at_trajectory_end: true
    constraints:
      stopped_velocity_tolerance: 0.02
      goal_time: 0.0
      joint_1: { trajectory: 0.2, goal: 0.02 }
      joint_2: { trajectory: 0.2, goal: 0.02 }
      joint_3: { trajectory: 0.2, goal: 0.02 }

    gains: # Required because we're controlling a velocity interface
      joint_1: { p: 10.0, d: 1.0, i: 1.0, i_clamp: 1.0 } # Smaller 'p' term, since ff term does most of the work
      joint_2: { p: 10.0, d: 1.0, i: 1.0, i_clamp: 1.0 }
      joint_3: { p: 10.0, d: 1.0, i: 1.0, i_clamp: 1.0 }

    velocity_ff:
      joint_1: 1.0
      joint_2: 1.0
      joint_3: 1.0
